"""Stable protocol constants for the APIMart MiniMax-H3 runner."""
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent.parent
H3_CLIENT = SCRIPTS_DIR / "run_apimart_minimax_h3.py"
PROMPT_KEY = "audited_content_only_prompt"
DASHSCOPE_DEFAULT_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DASHSCOPE_DEFAULT_MODEL = "qwen-vl-plus"
BRIDGE_KIND = "apimart_minimax_h3_online_qwen_bridge_v8_raw_image_prompt_video_atomic"
DEFAULT_STATIC_REFERENCE_COUNT = 1
GLOBAL_STYLE_REFERENCE_COUNT = 3
REFERENCE_IMAGE_COUNTS = (DEFAULT_STATIC_REFERENCE_COUNT, GLOBAL_STYLE_REFERENCE_COUNT)
H3_CANVAS_WIDTH = 1344
H3_CANVAS_HEIGHT = 768
H3_FRAME_COUNT = 107
H3_FPS = 24
OBSERVATION_FRAME_INDICES = (0, 26, 53, 80, 106)
QWEN_CONTEXT_FRAME_INDICES = OBSERVATION_FRAME_INDICES
PRIMARY_REFERENCE_FRAME_INDEX = QWEN_CONTEXT_FRAME_INDICES[0]
TEMPORAL_MIDDLE_FRAME_INDEX = QWEN_CONTEXT_FRAME_INDICES[len(QWEN_CONTEXT_FRAME_INDICES) // 2]
TEMPORAL_END_FRAME_INDEX = QWEN_CONTEXT_FRAME_INDICES[-1]
